### ISSUE TITLE
.TV HPE add articles / video segments

### ISSUE THREAD

**Issue by jasonjohnsonSA** [SADelivery/MASTER#11]
Follow up with Elise

**Comment by jasonjohnsonSA** [comment]
Assigning to May to follow up and do the audit - see your email

**Comment by may4media** [comment]
Audit follow-up  HPE http://www.siliconangle.tv/hpe-discover-2017/

 - Ken Won missing Blog
- Randy Meyer missing Blog
- Dr. Steven Pratt missing Blog
- please organize guests in alphabetical order
- Justin Hotard - no photo
- Dr. Eng Lim Goh: Image needs to be resized
- Michael Proper: missed Twitter: @michaelproper
Xavier Poisson: missing Twitter @cloudxp10
Craig McLellan- missing Twitter @CraigMcLellan
Steven Dietch- missing Twitter @stevendietch
Parvesh Sethi- missing Twitter: @pasethi
Peter Mckay- missing Twitter: @mckaypmckay2008
Tripp Partain - missing Twitter @tripppartain
Paul Sabin- missing Twitter @JustPauL
Susan Blocher- missiing Twitter @susanblocher17
Navin Mittal- missing Twitter @njmittal
Bill Mannel- - missing Twitter @Bill Mannel
Dr. Nicholas Nystrom - missing Twitter @nicknystrom
Denzil Samuels - missing Twitter @denzilsamuels
Jason Shropshire - missing Twitter @shr0p
Ana Pinczuk - missing Twitter @pinczuk
JR Fuller - missing Twitter @jrfuller321
Flynn Maloy - missing Twitter @flynnmaloy
Kate Swanborg - missing Twitter @kateswanborg
Randy Meyer- missing Twitter @Meyer_Randy
Kirk Bresniker - missing Twitter @kirkbresniker

**Comment by may4media** [comment]
-Randy Meyer - in shared schedule on day 3 @12:30 pm  https://www.youtube.com/watch?v=-yNrGqqncXc&list=PLenh213llmcanqpn9xXWIuSVijQncUhXt&index=38 
-Dr. Steven Pratt - in shared schedule on day 3 @12:30 pm  https://www.youtube.com/watch?v=-yNrGqqncXc&list=PLenh213llmcanqpn9xXWIuSVijQncUhXt&index=38
