### ISSUE TITLE
Chertoff Group - reorder .tv events

### ISSUE THREAD

**Issue by jasonjohnsonSA** [SADelivery/MASTER#131]
Fix and then figure out why this isn't happening properly from our checklist. 

---------- Forwarded message ---------
From: Casey Jaquez <casey.jaquez@chertoffgroup.com>
Date: Wed, Jun 28, 2017 at 6:12 PM
Subject: RE: theCUBE Coverage of Security in the Boardroom - Contract
To: Jason Johnson <jason.johnson@siliconangle.com>, Sam Kahane <sam.kahane@siliconangle.com>

Hey team!
 
Just wondering why our event doesn’t show up in chronological order in the upcoming events section of your website?
 
http://siliconangle.tv/category/upcoming-events/page/2/

**Comment by may4media** [comment]
Fixed
http://siliconangle.tv/category/upcoming-events
