### ISSUE TITLE
Share schedules with Elise AND update Friday checklist

### ISSUE THREAD

**Issue by jasonjohnsonSA** [SADelivery/MASTER#132]
Oh that's a great point Elise. May, she doesn't have an @siliconangle.com address so our standard Link-Share method excludes all but @siliconangle.com. All schedules that are created should be shared with Elise by the cube team on creation. This isn't happening so we can add that to our Monday checklist - "Share upcoming schedules with Elise"

For today, share the schedules you had sent Elise. 

Thanks!
J

**Comment by may4media** [comment]
done
