### ISSUE TITLE
Upcoming Events - SLA check

### ISSUE THREAD

**Issue by jasonjohnsonSA** [SADelivery/MASTER#26]

**Comment by may4media** [comment]
https://docs.google.com/a/siliconangle.com/document/d/1rCBRUt-jtRYsv1fnK4gI2wbE9n5mXvIFK-uyVVh6EPM/edit?usp=sharing

**Comment by may4media** [comment]
Nutanix https://docs.google.com/a/siliconangle.com/spreadsheets/d/1omvbPhEVGNeSrM08edpUArlmCQtSW3tft-ZUwRQx9bE/edit?usp=sharing

**Comment by may4media** [comment]
Updated
https://docs.google.com/a/siliconangle.com/document/d/1rCBRUt-jtRYsv1fnK4gI2wbE9n5mXvIFK-uyVVh6EPM/edit?usp=sharing

July 26- Node Summit 2017: is event confirmed? Note said “they want us back” (Jason)..shall we update the webpage or remove it? http://www.siliconangle.tv/node-summit-2017/ 
No SLA, No Guests (theCUBE Team)
SLA: No shared link
Guests: No Shared link 

July 11 - 13 MIT CDOIQ 2017: http://www.siliconangle.tv/mit-cdoiq-2017/ NO event..shall we remove from website? (Jason)
