### ISSUE TITLE
.TV audit of past weeks shows

### ISSUE THREAD

**Issue by jasonjohnsonSA** [SADelivery/MASTER#27]

**Comment by jasonjohnsonSA** [comment]
This is a check of the following:

Are guests on the page?
Do they have their SA.com blog posts linked?
Do they have their youtube segments linked?

**Comment by may4media** [comment]
Cloud Foundry Summit 2017 - All guests on page, including, youtube links, linked, and Twitter accounts.

**Comment by may4media** [comment]
**AWS-public-sector-2017** 
- Melvin Greer, missing Twitter: @Lead_Innovate, 
- Missing guest: Davis Johnson, VP of US Public Sector, Riverbed Technology 
- Andre Pienaar: not on the guest list yet posted on a web page, no youtube interview.was this misplaced from another event or was he a no-show?

**Comment by may4media** [comment]
**Pure 2017**
- Vik Nagjee, - Missing Twitter: @maxwell_musze), VP & CTO, Healthcare & Life Sciences, Pure Storage 
- Kent Petzold - Missing Twitter: (@klpetzold), Enterprise Storage Manager, Intermountain Healthcare 
- Ray Smith(: Missing Twitter @ras601), Assistant Executive Director for Technology, Mississippi Community College Board
- Andy Vandeveld, Missing Twitter @andyvandeveld, Veeam, VP of Global Strategic Alliances, Rajiev Rajavasireddy, Pure Storage, VP of Solutions

**Comment by may4media** [comment]
**Data Works 2017**
- Linton Ward: missing Twitter @Wardlinton 
- Alex Chen: missing Twitter: @AqchenIBM 
- Missing guest: Donna Prlich 
- Itamar Ankorian: missing Twitter @ItamarAnkorian

**Comment by may4media** [comment]
**AutoTech Council: On the Ground 2017**
- No video in web page
- All guests have no SA page blogs

**Comment by may4media** [comment]
**HPE 2017**
- not all guests are posted in alphabetical order 
- Partha Narasimhan: Font links are too big
- Justin Hotard: no photo
- Justin Hotard: Font links are too big
- Dr. Eng Lim Goh: Image needs to be resized
- Dr. Eng Lim Goh: Font links are too big
- Michael Proper: missed Twitter: @MichaelProper 
- Paul Miller: missed Twitter: @hep_ConvergedDI 
- Xavier Poisson: missing Twitter @CLOUDXP10 
- Craig McLellan- missing Twitter @CraigMcLellan
- Steven Dietch- missing Twitter @StevenDietch
- Parvesh Sethi- missing Twitter: @pasethi
- Peter Mckay- missing Twitter: @MckayPMckay2008 
- Tripp Partain - missing Twitter @TrippPartain
- Paul Sabin- missing Twitter @justpaul 
- Susan Blocher- missiing Twitter @SusanBlocher17
- Navin Mittal- missing Twitter @njmittal
- Bill Mannel- - missing Twitter @Bill Mannel
- Dr. Nicholas Nystrom - missing Twitter @nicknystrom 
- Denzil Samuels - missing Twitter @DenzilSamuels
- Jason Shropshire - missing Twitter @shr0p
- Ana Pinczuk - missing Twitter @pinczuk
- JR Fuller - missing Twitter @JRFuller321
- Flynn Maloy - missing Twitter @FlynnMaloy
- Kate Swanborg - missing Twitter @KateSwanborg
- Randy Meyer- missing Twitter @Meyer_Randy
- Kirk Bresniker - missing Twitter @KirkBresniker

**Comment by may4media** [comment]
**Spark Summit 2017**
- All guests have no SA page blogs
- Eric Siegel Twitter link does not work
-

**Comment by may4media** [comment]
**Subscribed 2017**
- All guests have no SA page blogs

**Comment by may4media** [comment]
All data here https://docs.google.com/a/siliconangle.com/document/d/1jlJaq98zMVcXvn5a7WcKHQWSnyBpRwj-VPBE6kSChfI/edit?usp=sharing

**Comment by may4media** [comment]
From Elise,
 
I do not see videos for the other people missing links on the page, can you verify whether they were guests?
-Bill Walker - was not interviewed 
-Kara Long - was not interviewed 
-Randy Meyer - in shared schedule on day 3 @12:30 pm  https://www.youtube.com/watch?v=-yNrGqqncXc&list=PLenh213llmcanqpn9xXWIuSVijQncUhXt&index=38 
-Dr. Steven Pratt - in shared schedule on day 3 @12:30 pm  https://www.youtube.com/watch?v=-yNrGqqncXc&list=PLenh213llmcanqpn9xXWIuSVijQncUhXt&index=38

**Comment by may4media** [comment]
Audit up to date as of July 10 2017 https://docs.google.com/document/d/1jlJaq98zMVcXvn5a7WcKHQWSnyBpRwj-VPBE6kSChfI/edit#
