### ISSUE TITLE
Upcoming Events - schedule email inquiry (14 days out)

### ISSUE THREAD

**Issue by jasonjohnsonSA** [SADelivery/MASTER#28]

**Comment by may4media** [comment]
can you elaborate on email inquiry?

**Comment by may4media** [comment]
Emailed Elise Monday, June 26, 2017, to input guest information in the SA. tv website

**Comment by may4media** [comment]
waiting to hear back from theCUBE team to share the shared link with Elise

uly 26- Node Summit 2017: is event confirmed? Note said “they want us back” (Jason)..shall we update the webpage or remove it? http://www.siliconangle.tv/node-summit-2017/
No SLA, No Guests (theCUBE Team)
SLA: No shared link
Guests: No Shared link
