### ISSUE TITLE
Confirm guests for HPE

### ISSUE THREAD

**Issue by jasonjohnsonSA** [SADelivery/MASTER#53]
Go here: http://siliconangle.tv/hpe-discover-2017/ 
Open the HPE internal schedule
Ensure the people below (and listed on the sa.tv hpe page) were guests that showed up etc
If any of them were guests then hit youtube/siliconangle and see if they're in the playlist. 
Report back here - add label "QA needed" tag to this issue in GIT

From Elise,

I do not see videos for the other people missing links on the page, can you verify whether they were guests? 
-Bill Walker
-Kara Long
-Randy Meyer
-Dr. Steven Pratt

**Comment by jasonjohnsonSA** [comment]
Comment test

**Comment by may4media** [comment]
From Elise,
 
I do not see videos for the other people missing links on the page, can you verify whether they were guests?
-Bill Walker - was not interviewed 
-Kara Long - was not interviewed 
-Randy Meyer - in shared schedule on day 3 @12:30 pm  https://www.youtube.com/watch?v=-yNrGqqncXc&list=PLenh213llmcanqpn9xXWIuSVijQncUhXt&index=38 
-Dr. Steven Pratt - in shared schedule on day 3 @12:30 pm  https://www.youtube.com/watch?v=-yNrGqqncXc&list=PLenh213llmcanqpn9xXWIuSVijQncUhXt&index=38
