### ISSUE TITLE
Newsletter time research - convert to a presentation

### ISSUE THREAD

**Issue by jasonjohnsonSA** [SADelivery/MASTER#59]
http://optinmonster.com/the-best-time-to-send-emails-heres-what-studies-show/

**Comment by may4media** [comment]
Great article, I think though the research would have been better if it was more specific to the industry.  The study doesn't tell what are the persona types of the users.  For example, working users vs nonworking.  work email vs personal email, etc.  
Although based on this the majority is Monday mornings prior to 10 am for each user time zone I am assuming for work emails during work hours.  It gives an opportunity to read the newsletter, reflect, and then implement and it helps the user on planning their working week based on it.
