### ISSUE TITLE
Build out newsletter product owner processes

### ISSUE THREAD

**Issue by jasonjohnsonSA** [SADelivery/MASTER#65]
Map out timers, email communications needed, time to deliver assets, etc. A full blown process from resource collection to hitting send in constant contact. Easier to discuss in person. Ping me when you're on to this task.

**Comment by may4media** [comment]
Follow-up Messages Template
https://docs.google.com/a/siliconangle.com/document/d/1hDa2wIGNqe-9d5KYL4iO4r1OoHNB1qXaBd60kOsuvvc/edit?usp=sharing

Marketing Checklist
https://docs.google.com/a/siliconangle.com/spreadsheets/d/1w0MDa33fEttiei035ViX8ad2c5UQ0wdc8BorPRyREls/edit?usp=sharing

**Comment by jasonjohnsonSA** [comment]
Made notes in messaging template. 
https://docs.google.com/document/d/1hDa2wIGNqe-9d5KYL4iO4r1OoHNB1qXaBd60kOsuvvc/edit

**Comment by may4media** [comment]
here is the update based on your feedback https://docs.google.com/a/siliconangle.com/document/d/1hDa2wIGNqe-9d5KYL4iO4r1OoHNB1qXaBd60kOsuvvc/edit?usp=sharing
