### ISSUE TITLE
Atunity video clipper work - sales support

### ISSUE THREAD

**Issue by jasonjohnsonSA** [SADelivery/MASTER#67]
See email 

---------- Forwarded message ----------
From: Carole Gunst <Carole.Gunst@attunity.com>
Date: Fri, Jun 23, 2017 at 11:12 AM
Subject: Re: Can Attunity edit a CUBE video for our use?
To: John Greco <john.greco@siliconangle.com>

John – here’s where I’d like to get clips for https://www.youtube.com/watch?v=eUccjH2UYCU. It broke so that it makes most sense to do 4 clips. Let me know if that’s a problem.
 
Verizon:
8:20 – 9:08
9:20 – 9:56
9:58 – 11:10
 
Attunity Compose for Hive
13:21 – 14:00

**Comment by may4media** [comment]
Verizon:
8:20 – 9:08  https://www.youtube.com/embed/eUccjH2UYCU?start=499&end=549&rel=0&autoplay=1 
9:20 – 9:56 https://www.youtube.com/embed/eUccjH2UYCU?start=558&end=599&rel=0&autoplay=1 
9:58 – 11:10 https://www.youtube.com/embed/eUccjH2UYCU?start=598&end=672&rel=0&autoplay=1 
 
Attunity Compose for Hive
13:21 – 14:00 https://www.youtube.com/embed/eUccjH2UYCU?start=799&end=842&rel=0&autoplay=1
