### ISSUE TITLE
.tv page "When IoT meets..." missing info, reg link, guests, etc 

### ISSUE THREAD

**Issue by may4media** [SADelivery/MASTER#82]
May - this event does not have event description nor guests listed or a registration link
http://www.siliconangle.tv/when-iot-meets-ai/ 

Jason - I inquired. I'll keep you posted.

**Comment by jasonjohnsonSA** [comment]
They shared the schedule: https://docs.google.com/spreadsheets/d/18fez5Z3nAE2Hl6SYK3Ud1p0hfraKC8Wlka9OsHmPUps/edit?ts=59515df9#gid=0
